server:
  port: 8080

eureka:
  instance:
    hostname: ${HOSTNAME:rally}
  client:
    serviceUrl:
      defaultZone: http://registry:8761/eureka/

rp:
  mongo:
    uri: mongodb://mongodb:27017

spring:
  cloud:
    consul:
      host: registry
      discovery:
        hostname: ${HOSTNAME:rally}
        prefer-ip-address: false
